services:
  backend:
    build:
      context: ./backend
      target: prod
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - db-data:/data/db
      - file-storage:/data/files
    restart: unless-stopped

volumes:
  db-data:
  file-storage:
